using System; // 系统基础命名空间
using System.Collections.Generic; // 集合类支持
using System.Reflection; // 反射相关操作
using System.Runtime.CompilerServices; // 运行时编译特性
using Helpers; // 自定义辅助工具
using TaleWorlds.CampaignSystem; // 战役系统核心
using TaleWorlds.CampaignSystem.GameState; // 游戏状态管理
using TaleWorlds.CampaignSystem.Inventory; // 库存系统
using TaleWorlds.CampaignSystem.MapEvents; // 地图事件
using TaleWorlds.CampaignSystem.Party; // 队伍管理
using TaleWorlds.CampaignSystem.Roster; // 物品清单
using TaleWorlds.CampaignSystem.Settlements; // 聚居地相关
using TaleWorlds.Core; // 核心功能
using TaleWorlds.Library; // 基础库支持
using TaleWorlds.Localization; // 本地化支持

namespace New_ZZZF // 自定义命名空间
{
    public class SkillInventoryScreenHelper // 独立类（新版 InventoryScreenHelper 已变为静态类，不可继承）
    {
        // 当前库存模式属性
        public InventoryScreenHelper.InventoryMode CurrentMode
        {
            set { _currentMode = value; }
            get { return _currentMode; }
        }

        // 当前库存逻辑快捷访问
        public static InventoryLogic InventoryLogic => Instance._inventoryLogic;

        // 玩家接受交易报价
        public void PlayerAcceptTradeOffer()
        {
            _inventoryLogic?.SetPlayerAcceptTraderOffer();
        }

        // 关闭库存界面
        public void CloseInventoryPresentation(bool fromCancel)
        {
            if (_inventoryLogic?.DoneLogic() == true)
            {
                Game.Current.GameStateManager.PopState(0);
                _doneLogicExtrasDelegate?.Invoke();
                _doneLogicExtrasDelegate = null;
                _inventoryLogic = null;
            }
        }

        // 打开库存界面（内部使用）
        private void OpenInventoryPresentation(TextObject leftRosterName)
        {
            var itemRoster = new ItemRoster();

            // 非测试模式下填充书籍物品
            if (TestCommonBase.BaseInstance == null || !TestCommonBase.BaseInstance.IsTestEnabled)
            {
                foreach (var item in Game.Current.ObjectManager.GetObjectTypeList<ItemObject>())
                {
                    if (item.ItemType == ItemObject.ItemTypeEnum.Book)
                        itemRoster.AddToCounts(item, 10);
                }
            }

            // 初始化库存逻辑
            _inventoryLogic = new InventoryLogic(null);
            _inventoryLogic.Initialize(
                itemRoster,
                new ItemRoster(),
                MobileParty.MainParty.MemberRoster,
                false,
                false,
                CharacterObject.PlayerCharacter,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                true,
                Instance._currentMode,
                leftRosterName,
                null,
                null
            );

            // 切换游戏状态
            var inventoryState = Game.Current.GameStateManager.CreateState<SkillInventoryState>();
            inventoryState.SetInventoryLogic(_inventoryLogic);
            Game.Current.GameStateManager.PushState(inventoryState, 0);
        }

        // 获取当前市场数据（支持村庄/城镇/模拟数据）
        private static IMarketData GetCurrentMarketData()
        {
            IMarketData marketData = null;
            if (Campaign.Current.GameMode == CampaignGameMode.Campaign)
            {
                var settlement = MobileParty.MainParty.CurrentSettlement;

                if (settlement != null)
                {
                    if (settlement.IsVillage)
                        marketData = settlement.Village.MarketData;
                    else if (settlement.IsTown)
                        marketData = settlement.Town.MarketData;
                }
            }
            return marketData ?? new FakeMarketData();
        }

        // 模拟市场数据实现
        internal class FakeMarketData : IMarketData
        {
            // 自动收集对象（反射支持）
            internal static void AutoGeneratedStaticCollectObjectsFakeMarketData(object o, List<object> collectedObjects)
            {
                ((FakeMarketData)o).AutoGeneratedInstanceCollectObjects(collectedObjects);
            }

            // 实例级对象收集
            protected virtual void AutoGeneratedInstanceCollectObjects(List<object> collectedObjects) { }

            // 获取物品基础价格
            public int GetPrice(ItemObject item, MobileParty tradingParty, bool isSelling, PartyBase merchantParty)
                => item.Value;

            // 获取装备元素价格
            public int GetPrice(EquipmentElement itemRosterElement, MobileParty tradingParty, bool isSelling, PartyBase merchantParty)
                => itemRosterElement.ItemValue;
        }

        // 打开子队伍库存界面
        public static void OpenScreenAsInventoryOfSubParty(MobileParty rightParty, MobileParty leftParty, DoneLogicExtrasDelegate doneDelegate)
        {
            var leader = rightParty.LeaderHero?.CharacterObject;
            var logic = new InventoryLogic(rightParty, leader, leftParty.Party);

            logic.Initialize(
                leftParty.ItemRoster,
                rightParty.ItemRoster,
                rightParty.MemberRoster,
                false,
                false,
                leader,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                null,
                null,
                null
            );

            Instance._doneLogicExtrasDelegate = doneDelegate;
            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = logic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 打开分解物品界面
        public static void OpenScreenAsInventoryForCraftedItemDecomposition(MobileParty party, CharacterObject character, DoneLogicExtrasDelegate doneDelegate)
        {
            Instance._inventoryLogic = new InventoryLogic(null);
            Instance._inventoryLogic.Initialize(
                new ItemRoster(),
                party.ItemRoster,
                party.MemberRoster,
                false,
                false,
                character,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                null,
                null,
                null
            );

            Instance._doneLogicExtrasDelegate = doneDelegate;
            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 打开队伍库存界面
        public static void OpenScreenAsInventoryOf(MobileParty party, CharacterObject character)
        {
            Instance._inventoryLogic = new InventoryLogic(null);
            Instance._inventoryLogic.Initialize(
                new ItemRoster(),
                party.ItemRoster,
                party.MemberRoster,
                false,
                true,
                character,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                null,
                null,
                null
            );

            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 打开双队伍库存界面
        public static void OpenScreenAsInventoryOf(PartyBase rightParty, PartyBase leftParty)
        {
            Instance._inventoryLogic = new InventoryLogic(leftParty);
            Instance._inventoryLogic.Initialize(
                leftParty.ItemRoster,
                rightParty.ItemRoster,
                rightParty.MemberRoster,
                false,
                false,
                rightParty.LeaderHero?.CharacterObject,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                null,
                leftParty.MemberRoster,
                null
            );

            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 打开默认库存界面
        public static void OpenScreenAsInventory(DoneLogicExtrasDelegate doneDelegate = null)
        {
            Instance._currentMode = InventoryScreenHelper.InventoryMode.Default;
            Instance.OpenInventoryPresentation(new TextObject("{=1234564}待选技能"));
            Instance._doneLogicExtrasDelegate = doneDelegate;
        }

        // 打开战斗战利品界面
        public static void OpenCampaignBattleLootScreen()
        {
            var lootDict = new Dictionary<PartyBase, ItemRoster>
            {
                { PartyBase.MainParty, new ItemRoster() /* TODO: MapEventSide.ItemRosterForPlayerLootShare removed in new API */ }
            };
            OpenScreenAsLoot(lootDict);
        }

        // 打开战利品分配界面
        public static void OpenScreenAsLoot(Dictionary<PartyBase, ItemRoster> itemRostersToLoot)
        {
            var leftRoster = itemRostersToLoot[PartyBase.MainParty];
            Instance._currentMode = InventoryScreenHelper.InventoryMode.Loot;
            Instance._inventoryLogic = new InventoryLogic(null);

            Instance._inventoryLogic.Initialize(
                leftRoster,
                MobileParty.MainParty.ItemRoster,
                MobileParty.MainParty.MemberRoster,
                false,
                true,
                CharacterObject.PlayerCharacter,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                null,
                null,
                null
            );

            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 打开仓库界面
        public static void OpenScreenAsStash(ItemRoster stash)
        {
            Instance._currentMode = InventoryScreenHelper.InventoryMode.Stash;
            Instance._inventoryLogic = new InventoryLogic(null);

            Instance._inventoryLogic.Initialize(
                stash,
                MobileParty.MainParty,
                false,
                false,
                CharacterObject.PlayerCharacter,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                new TextObject("{=nZbaYvVx}Stash"),
                null,
                null
            );

            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 打开带容量限制的仓库界面
        public static void OpenScreenAsWarehouse(ItemRoster stash, InventoryLogic.CapacityData capacity)
        {
            Instance._currentMode = InventoryScreenHelper.InventoryMode.Warehouse;
            Instance._inventoryLogic = new InventoryLogic(null);

            Instance._inventoryLogic.Initialize(
                stash,
                MobileParty.MainParty,
                false,
                false,
                CharacterObject.PlayerCharacter,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                new TextObject("{=anTRftmb}Warehouse"),
                null,
                capacity
            );

            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 打开物品接收界面
        public static void OpenScreenAsReceiveItems(ItemRoster items, TextObject leftName, DoneLogicExtrasDelegate doneDelegate = null)
        {
            Instance._currentMode = InventoryScreenHelper.InventoryMode.Default;
            Instance._inventoryLogic = new InventoryLogic(null);

            Instance._inventoryLogic.Initialize(
                items,
                MobileParty.MainParty.ItemRoster,
                MobileParty.MainParty.MemberRoster,
                false,
                true,
                CharacterObject.PlayerCharacter,
                InventoryScreenHelper.InventoryCategoryType.None,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                leftName,
                null,
                null
            );

            Instance._doneLogicExtrasDelegate = doneDelegate;
            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 打开商队交易界面
        public static void OpenTradeWithCaravanOrAlleyParty(MobileParty caravan, InventoryScreenHelper.InventoryCategoryType type)
        {
            Instance._currentMode = InventoryScreenHelper.InventoryMode.Trade;
            Instance._inventoryLogic = new InventoryLogic(caravan.Party);

            Instance._inventoryLogic.Initialize(
                caravan.Party.ItemRoster,
                PartyBase.MainParty.ItemRoster,
                PartyBase.MainParty.MemberRoster,
                true,
                true,
                CharacterObject.PlayerCharacter,
                type,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                null,
                null,
                null
            );

            Instance._inventoryLogic.SetInventoryListener(new CaravanInventoryListener(caravan));
            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);
        }

        // 激活当前聚居地交易
        public static void ActivateTradeWithCurrentSettlement()
        {
            OpenScreenAsTrade(
                Settlement.CurrentSettlement.ItemRoster,
                Settlement.CurrentSettlement.SettlementComponent,
                InventoryScreenHelper.InventoryCategoryType.None,
                null
            );
        }

        // 打开交易界面
        public static void OpenScreenAsTrade(ItemRoster leftRoster, SettlementComponent component, InventoryScreenHelper.InventoryCategoryType type, DoneLogicExtrasDelegate doneDelegate)
        {
            Instance._currentMode = InventoryScreenHelper.InventoryMode.Trade;
            Instance._inventoryLogic = new InventoryLogic(component.Owner);

            Instance._inventoryLogic.Initialize(
                leftRoster,
                PartyBase.MainParty.ItemRoster,
                PartyBase.MainParty.MemberRoster,
                true,
                true,
                CharacterObject.PlayerCharacter,
                type,
                GetCurrentMarketData(),
                false,
                Instance._currentMode,
                null,
                null,
                null
            );

            Instance._inventoryLogic.SetInventoryListener(new MerchantInventoryListener(component));
            Instance._doneLogicExtrasDelegate = doneDelegate;

            var state = Game.Current.GameStateManager.CreateState<InventoryState>();
            state.InventoryLogic = Instance._inventoryLogic;
            Game.Current.GameStateManager.PushState(state, 0);

            // TODO: FilterInventoryAtOpening removed from IInventoryStateHandler
        }

        // 物品类型转换
        public static InventoryScreenHelper.InventoryItemType GetInventoryItemTypeOfItem(ItemObject item)
        {
            if (item == null) return InventoryScreenHelper.InventoryItemType.None;
            return item.ItemType switch
            {
                ItemObject.ItemTypeEnum.Horse => InventoryScreenHelper.InventoryItemType.Horse,
                ItemObject.ItemTypeEnum.OneHandedWeapon => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.TwoHandedWeapon => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Polearm => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Arrows => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Bolts => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Shield => InventoryScreenHelper.InventoryItemType.Shield,
                ItemObject.ItemTypeEnum.Bow => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Crossbow => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Thrown => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Goods => InventoryScreenHelper.InventoryItemType.Goods,
                ItemObject.ItemTypeEnum.HeadArmor => InventoryScreenHelper.InventoryItemType.HeadArmor,
                ItemObject.ItemTypeEnum.BodyArmor => InventoryScreenHelper.InventoryItemType.BodyArmor,
                ItemObject.ItemTypeEnum.LegArmor => InventoryScreenHelper.InventoryItemType.LegArmor,
                ItemObject.ItemTypeEnum.HandArmor => InventoryScreenHelper.InventoryItemType.HandArmor,
                ItemObject.ItemTypeEnum.Pistol => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Musket => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Bullets => InventoryScreenHelper.InventoryItemType.Weapon,
                ItemObject.ItemTypeEnum.Animal => InventoryScreenHelper.InventoryItemType.Animal,
                ItemObject.ItemTypeEnum.Book => InventoryScreenHelper.InventoryItemType.Book,
                ItemObject.ItemTypeEnum.Cape => InventoryScreenHelper.InventoryItemType.Cape,
                ItemObject.ItemTypeEnum.HorseHarness => InventoryScreenHelper.InventoryItemType.HorseHarness,
                ItemObject.ItemTypeEnum.Banner => InventoryScreenHelper.InventoryItemType.Banner,
                _ => InventoryScreenHelper.InventoryItemType.None
            };
        }

        // 私有字段
        private InventoryScreenHelper.InventoryMode _currentMode; // 当前模式
        private InventoryLogic _inventoryLogic; // 库存逻辑
        private DoneLogicExtrasDelegate _doneLogicExtrasDelegate; // 完成回调
        // 单例实例
        private static readonly Lazy<SkillInventoryScreenHelper> _instance =
            new Lazy<SkillInventoryScreenHelper>(() => new SkillInventoryScreenHelper());
        // 单例访问器
        public static SkillInventoryScreenHelper Instance => _instance.Value;
        // 私有构造函数（单例）
        private SkillInventoryScreenHelper()
        {
        }

        // 库存分类枚举
        public enum InventoryCategoryType
        {
            None = -1,
            All,
            Armors,
            Weapon,
            Shield,
            HorseCategory,
            Goods,
            CategoryTypeAmount
        }

        // 完成操作委托
        public delegate void DoneLogicExtrasDelegate();

        // 商队交易监听器
        private class CaravanInventoryListener : InventoryListener
        {
            private readonly MobileParty _caravan;

            public CaravanInventoryListener(MobileParty caravan)
            {
                _caravan = caravan;
            }

            public override int GetGold() => _caravan.PartyTradeGold;
            public override TextObject GetTraderName() => _caravan.LeaderHero?.Name ?? _caravan.Name;
            public override void SetGold(int gold) => _caravan.PartyTradeGold = gold;
            public override PartyBase GetOppositeParty() => _caravan.Party;
            public override void OnTransaction() => throw new NotImplementedException();
        }

        // 商人交易监听器
        private class MerchantInventoryListener : InventoryListener
        {
            private readonly SettlementComponent _component;

            public MerchantInventoryListener(SettlementComponent component)
            {
                _component = component;
            }

            public override TextObject GetTraderName() => _component.Owner.Name;
            public override PartyBase GetOppositeParty() => _component.Owner;
            public override int GetGold() => _component.Gold;
            public override void SetGold(int gold) => _component.ChangeGold(gold - _component.Gold);
            public override void OnTransaction() => throw new NotImplementedException();
        }
    }
}